name: widget_scan
description: Scan all widgets in the project and process them accordingly.
version: 0.0.1
homepage: https://github.com/Nomeleel/widget_scan/blob/master/README.md
repository: https://github.com/Nomeleel/widget_scan

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

